package reverse

import (
	"encoding/json"
	"fmt"
	"html"
	"os"
	"regexp"
	"strconv"
	"strings"
)

// ParseHTMLFile parses an HTML file generated by pptx2html (GenerateHTMLFromParsed)
// back into a ParsedDoc structure, enabling HTML→PPTX roundtrip.
func ParseHTMLFile(htmlPath string) (*ParsedDoc, error) {
	data, err := os.ReadFile(htmlPath)
	if err != nil {
		return nil, fmt.Errorf("cannot read HTML: %w", err)
	}
	return ParseHTMLString(string(data))
}

// ParseHTMLString parses HTML string into ParsedDoc.
func ParseHTMLString(htmlStr string) (*ParsedDoc, error) {
	doc := &ParsedDoc{}

	// Extract slide dimensions from CSS: .slide { ... width:WIDTHpx; height:HEIGHTpx; ... }
	slideCSSRe := regexp.MustCompile(`\.slide\s*\{[^}]*width:\s*([\d.]+)px[^}]*height:\s*([\d.]+)px`)
	if m := slideCSSRe.FindStringSubmatch(htmlStr); m != nil {
		w, _ := strconv.ParseFloat(m[1], 64)
		h, _ := strconv.ParseFloat(m[2], 64)
		// px → pt (CSS px / 1.333)
		doc.SlideWidth = w / 1.333
		doc.SlideHeight = h / 1.333
	}
	if doc.SlideWidth == 0 {
		doc.SlideWidth = 960
		doc.SlideHeight = 540
	}

	// Split by <div class="slide"
	slideBlocks := splitSlides(htmlStr)
	doc.SlideCount = len(slideBlocks)

	for si, block := range slideBlocks {
		slide := ParsedSlide{SlideIndex: si + 1}

		// Extract slide background
		bgRe := regexp.MustCompile(`class="slide"\s+style="([^"]*)"`)
		if m := bgRe.FindStringSubmatch(block); m != nil {
			slide.BackgroundColor = extractCSSProp(m[1], "background")
		}

		// Extract shapes
		slide.Shapes = parseShapesFromHTML(block)
		doc.Slides = append(doc.Slides, slide)
	}

	return doc, nil
}

// splitSlides splits HTML into per-slide blocks
func splitSlides(htmlStr string) []string {
	marker := `<div class="slide"`
	parts := strings.Split(htmlStr, marker)
	var blocks []string
	for i := 1; i < len(parts); i++ {
		// Find the matching closing </div> for this slide
		// The slide div ends just before the next slide or </body>
		block := marker + parts[i]
		blocks = append(blocks, block)
	}
	return blocks
}

// parseShapesFromHTML extracts all .shape divs from a slide block
func parseShapesFromHTML(slideBlock string) []ParsedShape {
	var shapes []ParsedShape
	pt2px := 1.333
	globalID := 1

	// Find all shape openings and extract content
	shapeOpenRe := regexp.MustCompile(`<div class="shape" style="([^"]*)"`)
	openMatches := shapeOpenRe.FindAllStringSubmatchIndex(slideBlock, -1)

	for i, match := range openMatches {
		styleStart := match[2]
		styleEnd := match[3]
		style := slideBlock[styleStart:styleEnd]
		
		// Content is between this shape's > and its closing
		contentStart := match[1] // end of the opening tag match
		// Find the > after style attribute
		gtIdx := strings.Index(slideBlock[contentStart:], ">")
		if gtIdx == -1 { continue }
		contentStart = contentStart + gtIdx + 1

		var contentEnd int
		if i+1 < len(openMatches) {
			contentEnd = openMatches[i+1][0]
		} else {
			contentEnd = len(slideBlock)
		}
		// Trim trailing </div>
		content := slideBlock[contentStart:contentEnd]
		if idx := strings.LastIndex(content, "</div>"); idx >= 0 {
			content = content[:idx]
		}

		shape := ParsedShape{ID: globalID, Type: "AUTO"}
		globalID++

		// Parse CSS position properties
		shape.X = extractCSSFloat(style, "left") / pt2px
		shape.Y = extractCSSFloat(style, "top") / pt2px
		shape.W = extractCSSFloat(style, "width") / pt2px
		shape.H = extractCSSFloat(style, "height") / pt2px

		// Rotation
		rotRe := regexp.MustCompile(`transform:\s*rotate\(([\d.-]+)deg\)`)
		if m := rotRe.FindStringSubmatch(style); m != nil {
			shape.Rotation, _ = strconv.ParseFloat(m[1], 64)
		}

		// Border
		borderRe := regexp.MustCompile(`border:([\d.]+)px\s+solid\s+(#[0-9a-fA-F]+|[a-z]+)`)
		if m := borderRe.FindStringSubmatch(style); m != nil {
			shape.BorderWidth, _ = strconv.ParseFloat(m[1], 64)
			shape.BorderWidth /= pt2px
			shape.BorderColor = m[2]
		}

		// Border radius
		if strings.Contains(style, "border-radius:50%") {
			shape.ShapeType = "ellipse"
		} else if strings.Contains(style, "border-radius:12px") {
			shape.ShapeType = "roundRect"
			shape.BorderRadius = 0.05
		}

		// Clip-path based shapes
		if strings.Contains(style, "clip-path:polygon(50% 0%, 0% 100%, 100% 100%)") {
			shape.ShapeType = "triangle"
		} else if strings.Contains(style, "clip-path:polygon(50% 0%, 100% 50%, 50% 100%, 0% 50%)") {
			shape.ShapeType = "diamond"
		}

		// Shadow
		if strings.Contains(style, "box-shadow:") {
			shape.HasShadow = true
			shape.ShadowColor = "rgba(0,0,0,0.3)"
		}

		// Background / Fill
		bgVal := extractCSSProp(style, "background")
		parseFillFromCSS(bgVal, &shape)

		// Padding → shape text padding
		padRe := regexp.MustCompile(`padding:([\d.]+)px\s+([\d.]+)px\s+([\d.]+)px\s+([\d.]+)px`)
		if m := padRe.FindStringSubmatch(style); m != nil {
			shape.PadT, _ = strconv.ParseFloat(m[1], 64)
			shape.PadR, _ = strconv.ParseFloat(m[2], 64)
			shape.PadB, _ = strconv.ParseFloat(m[3], 64)
			shape.PadL, _ = strconv.ParseFloat(m[4], 64)
		}

		// Vertical align from justify-content
		if strings.Contains(style, "justify-content:center") {
			shape.Valign = "ctr"
		} else if strings.Contains(style, "justify-content:flex-end") {
			shape.Valign = "b"
		}

		// Check content type
		content = strings.TrimSpace(content)

		if strings.Contains(content, "<img ") && !strings.Contains(content, "<table") {
			// Image shape
			parseImageFromHTML(content, &shape)
		} else if strings.Contains(content, "<table class=\"ppt-table\"") {
			// Table shape
			parseTableFromHTML(content, &shape, pt2px)
		} else if strings.Contains(content, "<svg") {
			// Chart SVG
			shape.ChartSVG = content
		} else if strings.Contains(content, "<p ") || strings.Contains(content, "<span") {
			// Text shape
			parseTextFromHTML(content, &shape, pt2px)
		}

		shapes = append(shapes, shape)
	}

	return shapes
}

// parseFillFromCSS parses CSS background value into shape fill properties
func parseFillFromCSS(bg string, shape *ParsedShape) {
	bg = strings.TrimSpace(bg)
	if bg == "" || bg == "transparent" {
		shape.FillType = "none"
		return
	}

	if strings.HasPrefix(bg, "linear-gradient") {
		shape.FillType = "gradient"
		// Parse angle
		angleRe := regexp.MustCompile(`linear-gradient\(\s*(\d+)deg`)
		if m := angleRe.FindStringSubmatch(bg); m != nil {
			shape.GradientAngle, _ = strconv.ParseFloat(m[1], 64)
		}
		// Parse stops
		stopRe := regexp.MustCompile(`(#[0-9a-fA-F]{3,8}|rgba?\([^)]+\))\s*([\d.]+)%`)
		matches := stopRe.FindAllStringSubmatch(bg, -1)
		for _, m := range matches {
			pos, _ := strconv.ParseFloat(m[2], 64)
			color := m[1]
			alpha := 1.0
			if strings.HasPrefix(color, "rgba") {
				rc := regexp.MustCompile(`rgba\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*([\d.]+)\s*\)`)
				if rm := rc.FindStringSubmatch(color); rm != nil {
					r, _ := strconv.Atoi(rm[1])
					g, _ := strconv.Atoi(rm[2])
					b, _ := strconv.Atoi(rm[3])
					alpha, _ = strconv.ParseFloat(rm[4], 64)
					color = fmt.Sprintf("#%02X%02X%02X", r, g, b)
				}
			}
			shape.GradientStops = append(shape.GradientStops, GradientStop{
				Color:    color,
				Position: int(pos * 1000),
				Alpha:    alpha,
			})
		}
		return
	}

	if strings.HasPrefix(bg, "rgba") {
		rc := regexp.MustCompile(`rgba\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*([\d.]+)\s*\)`)
		if m := rc.FindStringSubmatch(bg); m != nil {
			r, _ := strconv.Atoi(m[1])
			g, _ := strconv.Atoi(m[2])
			b, _ := strconv.Atoi(m[3])
			a, _ := strconv.ParseFloat(m[4], 64)
			shape.FillType = "solid"
			shape.FillColor = fmt.Sprintf("#%02X%02X%02X", r, g, b)
			shape.FillTransparency = 1.0 - a
		}
		return
	}

	if strings.HasPrefix(bg, "#") || strings.HasPrefix(bg, "rgb(") {
		shape.FillType = "solid"
		if strings.HasPrefix(bg, "rgb(") {
			rc := regexp.MustCompile(`rgb\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)`)
			if m := rc.FindStringSubmatch(bg); m != nil {
				r, _ := strconv.Atoi(m[1])
				g, _ := strconv.Atoi(m[2])
				b, _ := strconv.Atoi(m[3])
				shape.FillColor = fmt.Sprintf("#%02X%02X%02X", r, g, b)
			}
		} else {
			shape.FillColor = bg
		}
		return
	}

	shape.FillType = "none"
}

// parseImageFromHTML extracts image info from shape content
func parseImageFromHTML(content string, shape *ParsedShape) {
	imgRe := regexp.MustCompile(`<img\s+src="([^"]*)"[^>]*alt="([^"]*)"[^>]*style="([^"]*)"`)
	m := imgRe.FindStringSubmatch(content)
	if m == nil { return }

	shape.ImagePath = m[1]
	shape.Name = html.UnescapeString(m[2])

	// Parse crop from inner img style (position:absolute;width:W%;height:H%;left:L%;top:T%)
	imgStyle := m[3]
	wPct := extractCSSFloat(imgStyle, "width")
	hPct := extractCSSFloat(imgStyle, "height")
	lPct := extractCSSFloat(imgStyle, "left")
	tPct := extractCSSFloat(imgStyle, "top")

	if wPct > 0 && hPct > 0 {
		// Reverse: imgW = 100/vw → vw = 100/imgW, cropL = -imgL/imgW
		vw := 100.0 / wPct
		vh := 100.0 / hPct
		if wPct != 100 || hPct != 100 || lPct != 0 || tPct != 0 {
			shape.CropL = -lPct / wPct
			shape.CropT = -tPct / hPct
			shape.CropR = 1.0 - vw - shape.CropL
			shape.CropB = 1.0 - vh - shape.CropT
		}
	}
}

// parseTextFromHTML extracts text runs from shape content
func parseTextFromHTML(content string, shape *ParsedShape, pt2px float64) {
	shape.HasText = true

	// Split paragraphs
	paraRe := regexp.MustCompile(`(?s)<p class="para"[^>]*style="([^"]*)"[^>]*>(.*?)</p>`)
	paraMatches := paraRe.FindAllStringSubmatch(content, -1)

	for _, pm := range paraMatches {
		paraStyle := pm[1]
		paraContent := pm[2]

		align := 0 // left
		if strings.Contains(paraStyle, "text-align:center") { align = 2 }
		if strings.Contains(paraStyle, "text-align:right") { align = 3 }

		// Extract line-height from paragraph
		lineHeight := 0.0
		lhRe := regexp.MustCompile(`line-height:\s*([\d.]+)`)
		if lhm := lhRe.FindStringSubmatch(paraStyle); lhm != nil {
			lineHeight, _ = strconv.ParseFloat(lhm[1], 64)
		}

		// Extract spans
		spanRe := regexp.MustCompile(`(?s)<span\s+style="([^"]*)">(.*?)</span>`)
		spanMatches := spanRe.FindAllStringSubmatch(paraContent, -1)

		isFirstRun := true
		for _, sm := range spanMatches {
			spanStyle := sm[1]
			text := sm[2]

			// Unescape HTML entities
			text = html.UnescapeString(text)
			text = strings.ReplaceAll(text, "<br>", "\n")

			if text == "" { continue }

			run := TextRun{
				Text:  text,
				Align: align,
			}

			// Font family
			ffRe := regexp.MustCompile(`font-family:\s*'([^']*)'`)
			if fm := ffRe.FindStringSubmatch(spanStyle); fm != nil {
				run.Font = fm[1]
				if run.Font == "+mn-ea" {
					run.Font = "Freesentation"
				}
			}

			// Font size (px → pt)
			fsRe := regexp.MustCompile(`font-size:\s*([\d.]+)px`)
			if fm := fsRe.FindStringSubmatch(spanStyle); fm != nil {
				szPx, _ := strconv.ParseFloat(fm[1], 64)
				run.Size = szPx / pt2px
			}

			// Color
			clrRe := regexp.MustCompile(`(?:^|;)\s*color:\s*(#[0-9a-fA-F]+|[a-z]+)`)
			if fm := clrRe.FindStringSubmatch(spanStyle); fm != nil {
				run.Color = fm[1]
			}

			// Bold
			if strings.Contains(spanStyle, "font-weight:bold") {
				run.Bold = -1
			}

			// Italic
			if strings.Contains(spanStyle, "font-style:italic") {
				run.Italic = -1
			}

			// Underline
			if strings.Contains(spanStyle, "text-decoration:underline") {
				run.Underline = -1
			}

			// Bullet (• prefix)
			if strings.HasPrefix(text, "• ") {
				run.Bullet = 1
				run.Text = strings.TrimPrefix(text, "• ")
			}

			// Line spacing on first run of paragraph
			if isFirstRun && lineHeight > 0 {
				run.LineSpace = lineHeight
			}

			isFirstRun = false
			shape.TextRuns = append(shape.TextRuns, run)
		}

		// Add newline after paragraph (except text already ends with \n)
		if len(shape.TextRuns) > 0 {
			last := &shape.TextRuns[len(shape.TextRuns)-1]
			if !strings.HasSuffix(last.Text, "\n") {
				last.Text += "\n"
			}
		}
	}

	// Trim trailing newline from last run
	if len(shape.TextRuns) > 0 {
		last := &shape.TextRuns[len(shape.TextRuns)-1]
		last.Text = strings.TrimRight(last.Text, "\n")
	}
}

// parseTableFromHTML extracts table data from shape content
func parseTableFromHTML(content string, shape *ParsedShape, pt2px float64) {
	// Column widths
	colRe := regexp.MustCompile(`<col\s+style="width:(\d+)px"`)
	colMatches := colRe.FindAllStringSubmatch(content, -1)
	for _, cm := range colMatches {
		w, _ := strconv.ParseFloat(cm[1], 64)
		shape.TableColWidths = append(shape.TableColWidths, w)
	}

	// Rows
	trRe := regexp.MustCompile(`(?s)<tr[^>]*>(.*?)</tr>`)
	trMatches := trRe.FindAllStringSubmatch(content, -1)
	shape.TableRows = len(trMatches)

	// Row heights
	trHRe := regexp.MustCompile(`<tr\s+style="height:(\d+)px"`)
	for _, tr := range trHRe.FindAllStringSubmatch(content, -1) {
		h, _ := strconv.ParseFloat(tr[1], 64)
		shape.TableRowHeights = append(shape.TableRowHeights, h)
	}

	maxCols := 0
	for _, trm := range trMatches {
		rowHTML := trm[1]
		tdRe := regexp.MustCompile(`(?s)<td([^>]*)>(.*?)</td>`)
		tdMatches := tdRe.FindAllStringSubmatch(rowHTML, -1)

		var cells []TableCellData
		for _, tdm := range tdMatches {
			attrs := tdm[1]
			cellText := tdm[2]
			// Strip HTML tags from cell text but preserve <br> as \n
			cellText = strings.ReplaceAll(cellText, "<br>", "\n")
			cellText = regexp.MustCompile(`<[^>]*>`).ReplaceAllString(cellText, "")
			cellText = html.UnescapeString(cellText)

			cell := TableCellData{Text: cellText}

			// Parse style from td attributes
			styleRe := regexp.MustCompile(`style="([^"]*)"`)
			if sm := styleRe.FindStringSubmatch(attrs); sm != nil {
				tdStyle := sm[1]
				// Color
				if cm := regexp.MustCompile(`(?:^|;)\s*color:\s*(#[0-9a-fA-F]+|[a-z]+)`).FindStringSubmatch(tdStyle); cm != nil {
					cell.Color = cm[1]
				}
				// Bold
				if strings.Contains(tdStyle, "font-weight:bold") {
					cell.Bold = -1
				}
				// Font size
				if fm := regexp.MustCompile(`font-size:\s*([\d.]+)px`).FindStringSubmatch(tdStyle); fm != nil {
					sz, _ := strconv.ParseFloat(fm[1], 64)
					cell.Size = sz / pt2px / 0.96
				}
				// Background
				if bm := regexp.MustCompile(`background:\s*(#[0-9a-fA-F]+)`).FindStringSubmatch(tdStyle); bm != nil {
					cell.Bg = bm[1]
				}
				// Alignment
				if strings.Contains(tdStyle, "text-align:center") { cell.Align = "ctr" }
				if strings.Contains(tdStyle, "text-align:right") { cell.Align = "r" }
				// VAlign
				if strings.Contains(tdStyle, "vertical-align:middle") { cell.VAlign = "ctr" }
				if strings.Contains(tdStyle, "vertical-align:bottom") { cell.VAlign = "b" }
				// Borders
				if bdr := extractCSSProp(tdStyle, "border-top"); bdr != "" { cell.BdrT = bdr }
				if bdr := extractCSSProp(tdStyle, "border-bottom"); bdr != "" { cell.BdrB = bdr }
				if bdr := extractCSSProp(tdStyle, "border-left"); bdr != "" { cell.BdrL = bdr }
				if bdr := extractCSSProp(tdStyle, "border-right"); bdr != "" { cell.BdrR = bdr }
				// Padding
				padRe := regexp.MustCompile(`padding:\s*([\d.]+)px\s+([\d.]+)px\s+([\d.]+)px\s+([\d.]+)px`)
				if pm := padRe.FindStringSubmatch(tdStyle); pm != nil {
					cell.MarT, _ = strconv.ParseFloat(pm[1], 64)
					cell.MarR, _ = strconv.ParseFloat(pm[2], 64)
					cell.MarB, _ = strconv.ParseFloat(pm[3], 64)
					cell.MarL, _ = strconv.ParseFloat(pm[4], 64)
				}
			}

			// Colspan
			if cm := regexp.MustCompile(`colspan="(\d+)"`).FindStringSubmatch(attrs); cm != nil {
				cs, _ := strconv.Atoi(cm[1])
				cells = append(cells, cell)
				// Add merge-skip cells
				for j := 1; j < cs; j++ {
					cells = append(cells, TableCellData{MergeSkip: 1})
				}
				continue
			}

			// Rowspan
			if rm := regexp.MustCompile(`rowspan="(\d+)"`).FindStringSubmatch(attrs); rm != nil {
				// Mark as rowspan origin (vertMerge=0 is default)
			}

			cells = append(cells, cell)
		}

		if len(cells) > maxCols { maxCols = len(cells) }

		rowJSON, _ := json.Marshal(cells)
		shape.TableData = append(shape.TableData, json.RawMessage(rowJSON))
	}

	shape.TableCols = maxCols
}

// extractCSSProp extracts a CSS property value from a style string
func extractCSSProp(style, prop string) string {
	// Handle composite properties like "border-top"
	idx := strings.Index(style, prop+":")
	if idx == -1 { return "" }
	rest := style[idx+len(prop)+1:]
	end := strings.Index(rest, ";")
	if end == -1 { end = len(rest) }
	return strings.TrimSpace(rest[:end])
}

// extractCSSFloat extracts a float value from CSS like "left:123.4px"
func extractCSSFloat(style, prop string) float64 {
	re := regexp.MustCompile(prop + `:\s*(-?[\d.]+)(?:px|%)`)
	m := re.FindStringSubmatch(style)
	if m == nil { return 0 }
	v, _ := strconv.ParseFloat(m[1], 64)
	return v
}
